---
# tasks file for elk-setup

- name: Install Java 8
  include: java.yml

- name: Install Elasticsearch
  include: elasticsearch.yml

- name: Install Kibana
  include: kibana.yml

- name: Install Logstash
  include: logstash.yml


