---
- name: Copying yum repo for Metricbeat
  template: src=elastic.repo.j2 dest=/etc/yum.repos.d/elastic.repo owner=root group=root mode=0644

- name: Install Metricbeat
  yum: name=metricbeat state=installed

